// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbDp8SltRl18HowMqbCGvMaDzOTF9qn74',
    appId: '1:436824335953:web:a90abdd8e6bf1a9a7efa70',
    messagingSenderId: '436824335953',
    projectId: 'fir-bookmark-7f666',
    authDomain: 'fir-bookmark-7f666.firebaseapp.com',
    storageBucket: 'fir-bookmark-7f666.appspot.com',
    measurementId: 'G-9V3QLDRWP7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_ASJZsPRfzphb2-jDvTAJG-FCncJY6p0',
    appId: '1:436824335953:android:bd986cf1a6b46b517efa70',
    messagingSenderId: '436824335953',
    projectId: 'fir-bookmark-7f666',
    storageBucket: 'fir-bookmark-7f666.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVOmIkRYqfxHe3YHx4ZIn0XTEgcC3QP6w',
    appId: '1:436824335953:ios:b790a47a3468e3a37efa70',
    messagingSenderId: '436824335953',
    projectId: 'fir-bookmark-7f666',
    storageBucket: 'fir-bookmark-7f666.appspot.com',
    iosBundleId: 'com.example.timerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVOmIkRYqfxHe3YHx4ZIn0XTEgcC3QP6w',
    appId: '1:436824335953:ios:711c6b6379fbf8077efa70',
    messagingSenderId: '436824335953',
    projectId: 'fir-bookmark-7f666',
    storageBucket: 'fir-bookmark-7f666.appspot.com',
    iosBundleId: 'com.example.timerApp.RunnerTests',
  );
}
